### PR TITLE
convert func

### PR DESCRIPTION
**Pull request by STALLAAAA**
Closes #

#### Before submitting this PR, please make sure you have:

- [x] run `python -m pytest tests/` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited.

### CODE REVIEW

**Comment by YuanmingLeee** [comment]
1. Fix the coding style first with some formatting in your IDE.
2. Learn some Git knowledge, first setup your git workspace in your local computer, and commit multiple files at once. Also, squash your minor modifications into one or few commits, and then force push to your branch. 

I recommend you to use PyCharm (there is a free community version) for code formatting and Git GUI.

**Comment by YuanmingLeee** [comment]
If it is too difficult to write a test file, leave it. You can at least provide some test files so that we can try them on our computer.

**Comment by YuanmingLeee** [comment]
You cannot install tensorrt from pip. Pip does not provide the compiled wheel. 
Leave the unit test for others, please try fix the coding style and re arrange the functions.

**Comment by STALLAAAA** [comment]
> If it is too difficult to write a test file, leave it. You can at least provide some test files so that we can try them on our computer.

Thank you very much. I have learned about the runners of github action. And  if you hope to create a new workflow for gpu environment testing,  you could raise a new issue and i will try to fix it in the next 2 weeks. At present the test is run on vm while it seems that docker has api for nvidia cuda . Thus docker may be a better choice for the extending.

**Comment by STALLAAAA** [comment]
> 1. Fix the coding style first with some formatting in your IDE.
> 2. Learn some Git knowledge, first setup your git workspace in your local computer, and commit multiple files at once. Also, squash your minor modifications into one or few commits, and then force push to your branch.
> 
> I recommend you to use PyCharm (there is a free community version) for code formatting and Git GUI.

Awfully sorry for my disturbing pr. I am trying to learn more about git and will test codes in my fork repo before i make another pr.

**Comment by univerone** [comment]
> > 1. Fix the coding style first with some formatting in your IDE.
> > 2. Learn some Git knowledge, first setup your git workspace in your local computer, and commit multiple files at once. Also, squash your minor modifications into one or few commits, and then force push to your branch.
> > 
> > I recommend you to use PyCharm (there is a free community version) for code formatting and Git GUI.
> 
> Awfully sorry for my disturbing pr. I am trying to learn more about git and will test codes in my fork repo before i make another pr.

@STALLAAAA You don't have to make new pr,  new commits from your topic branch will be added to your existing pull request automatically. Besides, try to use command line to add new commits, and make a commit for a whole task instead of for a file.

**Comment by huangyz0918** [comment]
Please squash your commits and leave only necessary ones. @STALLAAAA

**Pull request closed without merging**
