### PR TITLE
:bug: fix model display issue

### LINKED ISSUE #178: Failed to get model information form both frontend webpage and fastapi
#### Software and Hardware Versions 
ModelCI v1.x.x, CUDA Version vx.x.x, GPU device used...

#### Problem description
visit `http://localhost:3333/#/` in the browser, the expected model information cannot be displayed.

Screenshot_2021-01-14 ML ModelCI

visit `http://localhost:8000/api/v1/model/` in the browser, neither did the expected data show, and the terminal has error output as following

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/fastapi/routing.py", line 183, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "~/miniconda3/envs/modelci/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "~/miniconda3/envs/modelci/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./modelci/app/v1/endpoints/model.py", line 27, in get_all_model
    return list(map(ModelListOut.from_bo, models))
  File "./modelci/types/vo/model_vo.py", line 188, in from_bo
    acc=model_bo.acc,
AttributeError: 'ModelBO' object has no attribute 'acc'
```

#### Steps to Reproduce the Problem

```bash
modelci start
cd frontend
npm install
npm start
```

#### Expected Behavior
Model information displayed in browser as expected

#### Other Information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
- [ ] change the url where front-end page used to get data from `http://localhost:5000` to `http://localhost:8000/api/v1/model/`
- [ ] modify `model_vo.py` to adapt to current model structure

### PR DESCRIPTION
**Pull request by univerone**
Closes #178 

#### What has been done to verify that this works as intended?

1. add icejs default port 3333 to env to address CORS related issues
2. introduce a config file for frontend project
3. make changes to fix model display issue due to recent database structure change.
4. enable display profile table for model without valid profiling data

Here is an example screenshot
Screenshot_2021-01-14 ML ModelCI

#### Does this change require updates to documentation?
Yes
#### Before submitting this PR, please make sure you have:

- [x] run `python -m pytest tests/` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited.

### CODE REVIEW

**Review by YuanmingLeee — APPROVED** [review]
lgtm

**Comment by HuaizhengZhang** [comment]
image
If the converted version is PyTorch, I suppose it is the original PyTorch version. Therefore, the serving engine should be ‘FastAPI‘ or leave it to 'blank' rather than 'torchscript'.

**Comment by HuaizhengZhang** [comment]
@univerone @YuanmingLeee

**Comment by univerone** [comment]
> image
> If the converted version is PyTorch, I suppose it is the original PyTorch version. Therefore, the serving engine should be ‘FastAPI‘ or leave it to 'blank' rather than 'torchscript'.

The format of this model is `torchscript`, the value of converted version here is by default the framework of this model, maybe converted version should be changed to Framework instead

**Comment by YuanmingLeee** [comment]
For the image shown above, the model is TorchScript, there is no issue.

I feel that if we save the original PyTorch native model, it should be as following:
```
Converted Version: None
Serving Engine: PyTorch
```

**Comment by univerone** [comment]
> For the image shown above, the model is TorchScript, there is no issue.
> 
> I feel that if we save the original PyTorch native model, it should be as following:
> 
> ```
> Converted Version: None
> Serving Engine: PyTorch
> ```

That's  reasonable

**Comment by HuaizhengZhang** [comment]
Great. We are convergence. Please fix the issue next PR.

**Comment by HuaizhengZhang** [comment]
So the above should be
```
Converted Version: TorchScript
Serving Engine：FastAPI
```

For the table，please combine the `framework， engine` as `Format`
**In this case, the format is torchscript**

**Pull request merged**
